# Generated by Django 5.2.4 on 2025-09-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_farmer',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a farmer'),
        ),
    ]
